# Generated by Django 2.1 on 2018-08-27 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='feed',
            field=models.CharField(blank=True, choices=[('medium', 'Medium')], max_length=15),
        ),
    ]
