# Generated by Django 2.1 on 2018-08-27 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profile_feed'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='unsplash',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='feed',
            field=models.CharField(blank=True, choices=[('medium', 'Medium'), ('unsplash', 'Unsplash')], max_length=15),
        ),
    ]
