# Generated by Django 2.1 on 2018-08-28 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnalytics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_visits', models.IntegerField(default=0)),
                ('facebook_visits', models.IntegerField(default=0)),
                ('github_visits', models.IntegerField(default=0)),
                ('linkedin_visits', models.IntegerField(default=0)),
                ('twitter_visits', models.IntegerField(default=0)),
                ('medium_visits', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
