# Generated by Django 2.1 on 2018-08-31 05:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_image'),
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileAnalytics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_visits', models.IntegerField(default=0)),
                ('facebook_visits', models.IntegerField(default=0)),
                ('github_visits', models.IntegerField(default=0)),
                ('linkedin_visits', models.IntegerField(default=0)),
                ('twitter_visits', models.IntegerField(default=0)),
                ('medium_visits', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Profile')),
            ],
        ),
        migrations.RemoveField(
            model_name='useranalytics',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserAnalytics',
        ),
    ]
