# Generated by Django 2.1 on 2018-09-05 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_auto_20180831_0546'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileanalytics',
            name='unsplash_visits',
            field=models.IntegerField(default=0),
        ),
    ]
