# Generated by Django 2.1 on 2018-08-21 06:59

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='end_date',
            field=models.DateTimeField(default=accounts.models.get_default_end_date),
        ),
    ]
